name: CI/CD Car & Louage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone le projet
        uses: actions/checkout@v3

      - name: Build image Docker
        run: docker build -t car-louage .

      - name: Lance les containers
        run: docker compose up -d

      - name: Vérifie que Apache répond
        run: curl -f http://localhost:8080 || exit 1

      - name: Arrête les containers
        run: docker compose down